### ISSUE TITLE
Support for V5

### ISSUE THREAD

**Issue by vaa7-ha** [J-shw/wdnas_client#31]
Hi, 

I saw your conversation in [#32](https://github.com/J-shw/ha-mycloud/issues/32#issuecomment-3284043802) and could maybe support. I'm running a WD My Cloud V5 (5.31.108) at home and by using inspect element and looking for POST requests I found the following: 

1. STATUS
http://10.0.0.1/cgi-bin/status_mgr.cgi
Request Method: POST
payload: cmd=resource
content-type: application/x-www-form-urlencoded; charset=UTF-8

Within the response same attributes are available as in V2 (mem_total, mem2_total, mem_free, cpu). For me this looks identical to the your implementation for V2. 

2. SYSINFO
http://10.0.0.1/xml/sysinfo.xml?id=1759694477345
Request Method: POST
payload: id = 1759694477345  # UNIX Timestamp

Within the response same attributes are available as in V2 (mem_total, mem2_total, mem_free, cpu). For me this looks identical to the your implementation for V2. 
I've shorten the response a bit:

```
<config>
	<disks>
		<disk id="1">
			<name>sda</name>
			[...]
			<sleep>0</sleep>
		</disk>
		<disk id="2">
			[...]
		</disk>
		<count>2</count>
	</disks>
	<update>
		<disk_healthy>0</disk_healthy>
	</update>
	<raids>
		<dirty>0</dirty>
		<raid id="1">
			[...]
		</raid>
	</raids>
	<updating>0</updating>
	<vols>
		<vol id="1">
			<num>1</num>
			[...]
			<state></state>
		</vol>
		<total_size>3893374910178</total_size>
		<total_used_size>514802823168</total_used_size>
		<total_unused_size>3378572087010</total_unused_size>
		<total_size_h>3.89 TB</total_size_h>
		<total_used_size_h>514 GB</total_used_size_h>
		<total_unused_size_h>3.38 TB</total_unused_size_h>
	</vols>
</config>
```

I hope this helps a little bit. Let me know if you need some more details or if I should look for other POST requests.

**Comment by J-shw** [comment]
> but the password is also hashed.

Right, so hopefully it uses the same hashing logic..

What I will start to do is build a new branch with some new logic for V5. 

I first up just want to get login working and then start seeing if any other endpoints have changed.

**Comment by vaa7-ha** [comment]
Hi @J-shw I updated the previous post.

**Comment by J-shw** [comment]
Haha its all good. 

Ok, could you try again with the latest commit I have pushed. I just removed an extra bit of content-type that was used in v2.

I changed ` "Content-Type": "application/json; charset=UTF-8",` to `"Content-Type": "application/json",`

**Comment by vaa7-ha** [comment]
I've updated the git with `pip install --upgrade git+https://github.com/J-shw/wdnas_client.git@feature/v5-support` and have run the `example-use.py` again. The result is the same: 

```
(.venv) USER wdnas_test % python3 example-use.py

Username: admin
Password: ***************
Traceback (most recent call last):
  File "/Users/USER/wdnas_test/example-use.py", line 22, in <module>
    asyncio.run(main())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/USER/wdnas_test/example-use.py", line 10, in main
    async with client(username, password, host, version) as wdNAS:
  File "/Users/USER/wdnas_test/.venv/lib/python3.9/site-packages/wdnas_client/__init__.py", line 23, in __aenter__
    await self.login()
  File "/Users/USER/wdnas_test/.venv/lib/python3.9/site-packages/wdnas_client/__init__.py", line 70, in login
    raise RequestFailedError(response.status)
wdnas_client.exceptions.RequestFailedError: Request failed: 415
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10a4534f0>
Unclosed connector
connections: ['deque([(<aiohttp.client_proto.ResponseHandler object at 0x10a4c2700>, 12.843653666)])']
connector: <aiohttp.connector.TCPConnector object at 0x10a45aa60>
```

**Comment by J-shw** [comment]
I just noticed you ran a modified login method only, and not the whole class. I have just updated the v5 branch with the new header, so see if that login works and then see if the other commands work or if they need changing too

**Comment by vaa7-ha** [comment]
Hey @J-shw,

sorry for the delay in getting back to you — I wasn’t able to test over the weekend, and I’m still learning my way around Python, so apologies if I miss something obvious 😅

I’ve now pulled the latest changes from the feature/v5-support branch and ran the example-use.py test again. The login still works perfectly (HTTP 200, cookies received), but I’m still getting the same TypeError when calling system_info().

Here’s the full output:

```
(.venv) USER wdnas_test % python3 example-use.py
Username: admin
Password: ***************
Login successful (HTTP 200)
Received cookies: ['fe97238703cba', 'ge41881ed8d9r']
Traceback (most recent call last):
  File "/Users/USER/wdnas_test/example-use.py", line 22, in <module>
    asyncio.run(main())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/USER/wdnas_test/example-use.py", line 11, in main
    print("System Info:", await wdNAS.system_info())
  File "/Users/USER/wdnas_test/.venv/lib/python3.9/site-packages/wdnas_client/__init__.py", line 98, in system_info
    async with self.session.get(url, headers=headers) as response:
  File "/Users/USER/wdnas_test/.venv/lib/python3.9/site-packages/aiohttp/client.py", line 1488, in __aenter__
    self._resp: _RetType = await self._coro
  File "/Users/USER/wdnas_test/.venv/lib/python3.9/site-packages/aiohttp/client.py", line 770, in _request
    resp = await handler(req)
  File "/Users/USER/wdnas_test/.venv/lib/python3.9/site-packages/aiohttp/client.py", line 746, in _connect_and_send_request
    resp = await req.send(conn)
  File "/Users/USER/wdnas_test/.venv/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1476, in send
    await writer.write_headers(status_line, self.headers)
  File "/Users/USER/wdnas_test/.venv/lib/python3.9/site-packages/aiohttp/http_writer.py", line 217, in write_headers
    buf = _serialize_headers(status_line, headers)
  File "aiohttp/_http_writer.pyx", line 148, in aiohttp._http_writer._serialize_headers
  File "aiohttp/_http_writer.pyx", line 109, in aiohttp._http_writer._write_str_raise_on_nlcr
TypeError: Cannot serialize non-str key None
```

Afterwards I added a debug print within the __init__

```
async def system_info(self):
    url = f"{SCHEME}{self.host}{ENDPOINTS[self.version]['system_info']}"

    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json"
    }

    print("\n=== DEBUG system_info() ===")
    print("URL:", url)
    print("HEADERS:", headers)
    print("COOKIES:", self.session.cookie_jar.filter_cookies(url))
    print("============================\n")

    async with self.session.get(url, headers=headers) as response:
        data = await response.text()
```

Here’s the output from system_info():

```
=== DEBUG system_info() ===
URL: http://192.168.10.41/xml/sysinfo.xml
HEADERS: {'Host': '192.168.10.41', 'X-CSRF-Token': None}
COOKIES: Set-Cookie: fe97238703c...
Set-Cookie: ge41881ed8d9...
============================
```

Let me know if I can do something else to help.

Thanks again for your patience and all the work you’re putting into this — it’s awesome to see this progressing! 🙏

**Comment by J-shw** [comment]
Look at that! First initial V5 support!

Ok the next error looks like an issue with parsing the response from the api. Might need to check if the API is correct and also what the response looks like.

**Comment by J-shw** [comment]
@vaa7-ha you legend. 

I will implement these soon and let you know when its ready to test again.

**Comment by vaa7-ha** [comment]
Perfect I run a test here are the results: 

✅ System Info OK: {'disks': [{'id': '1', 'name': 'sda', 'connected': True, 'vendor': 'WD', 'model': 'WDC WD40E', 'rev': '83.00A...

✅ Share Names OK: [{'share_name': 'Public', 'path': '/mnt/HD/HD_a2/Public'}, {'share_name': 'TimeMachineBackup', 'path': '/mnt/HD/HD_a2/Ti...

❌ System Status FAILED: RequestFailedError - Request failed: 500

✅ Network Info OK: {'00:00:[...]': {'speed': '1000', 'dhcp_enable': False, 'dns_manual': True, 'ip': '192.168.10.41', 'netmask': '25...

✅ Device Info OK: {'serial_number': 'WUBM311', 'name': 'MyCloudEX2Ultra', 'description': '2-Bay NAS'}...

✅ System Version OK: {'firmware': '5.31.108', 'oled': '1.06'}...

❌ Latest Version FAILED: RequestFailedError - Request failed: 500

✅ Accounts OK: {'users': [{'uid': '500', 'name': 'admin', 'email': 'abc@dfg.com', 'pwd': True, 'gid': '1000', 'first_name': ...

✅ Alerts OK: []...

Furthermore I checked the table and made changes **bold**: 

Method | API | Payload | check
-- | -- | -- | -- |
login | /nas/v1/auth | {"username":"user1","password":"alisdh2309oas"} | ✅ 
system_info | /xml/sysinfo.xml | **_=1761313901940** | ⚙️
share_names | /web/get_share_name_list.php | N/A | ✅ 
system_status | /cgi-bin/status_mgr.cgi | **cmd=resource** | ⚙️
device_info | /cgi-bin/system_mgr.cgi | cmd=cgi_get_device_info | ✅ 
system_version | /cgi-bin/system_mgr.cgi | cmd=get_firm_v_xml | ✅ 
latest_version | /cgi-bin/system_mgr.cgi | **not in V5** | ❌ 
accounts | /xml/account.xml | N/A | ✅ 
alerts | /cgi-bin/system_mgr.cgi | cmd=cgi_get_alert | ✅
